name: CI/CD using github hello
on: push
jobs:
    CICD:
        runs-on: ubuntu-latest
        steps:
         - name: installing-java
           uses: actions/setup-java@v3
           with:
             java-version: '17'
             distribution: 'temurin'

         - name: check
           run: |
             java -version
             javac -version
             mvn --version

         - name: clone project
           uses: actions/checkout@v3

         - name: clean output
           run: mvn clean

         - name: create output
           run: mvn package
        
         - name: target folder
           run: |
            cd target/classes
            java com.mycompany.app.Calculator